### ISSUE TITLE
Submit JavaScript based Program with Solution

### ISSUE THREAD

**Issue by diwakar1593** [diwakar1593/JavaScript-Problem#1]

**Comment by Vaishali785** [comment]
Hey @diwakar1593 Can you please describe what kind of program is required here?

**Comment by diwakar1593** [comment]
Hey @Vaishali785  you can contribute any kind of program but their solution must be code in JS. It is an repo to store javascript problem for enhancing you js skills!

**Comment by Vaishali785** [comment]
> Hey @Vaishali785 you can contribute any kind of program but their solution must be code in JS. It is an repo to store javascript problem for enhancing you js skills!

Okay, got it. I'll surely make the contribution here

**Comment by manthankhawse** [comment]
@diwakar1593 , I want to contribute to this repo, so basically I have take an algorithm based problem and provide its solution in javascript. Is that correct?

**Comment by diwakar1593** [comment]
@manthankhawse  Yes it is Correct.

**Comment by Vaishali785** [comment]
Hi @diwakar1593, I've generated one PR for JS program, please merge it as soon as possible.

**Comment by manthankhawse** [comment]
@diwakar1593 I have made a pull request as well, please look into it.

**Comment by diwakar1593** [comment]
@Vaishali785 @manthankhawse You for got to update the readme. Please update just write Question number and problem name

**Comment by Vaishali785** [comment]
> @Vaishali785 @manthankhawse You for got to update the readme. Please update just write Question number and problem name

@diwakar1593 readme file updated .

**Comment by diwakar1593** [comment]
@Vaishali785 Accepted! Thank you for your contribution.

**Comment by abhinaba-dash** [comment]
Hello @diwakar1593 can I also contribute into this?

**Comment by diwakar1593** [comment]
@abhinaba-dash yes

**Comment by mdfaizalam555** [comment]
kindly assign me ,  I want to work on this issue
